[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

# Redirect halaman login
[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

# Semua route lain ke index (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
